### ISSUE TITLE
[Bug] Update the package to support Dart 3

### ISSUE THREAD

**Issue by moosalim** [iamriajul/adhan-dart#49]
Hello @iamriajul , this package is outdated. can you please update it to be compatible with Dart 3 and null safety

**Comment by iamriajul** [comment]
PRs are welcomed.

**Comment by iamriajul** [comment]
You can use the Prerelease as of now: [adhan 2.0.0-nullsafety.2 | Dart Package (pub.dev)](https://pub.dev/packages/adhan/versions/2.0.0-nullsafety.2)

I'm trying to make it a stable release, but because of time shortage, I couldn't give much time previously.

Soon I'll try to release a stable version with null safety support. InShaaAllah.

**Comment by iamriajul** [comment]
Dart 3 support released in stable channel.
